# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  fastdeliveruuapi:
    image: fastdeliveruuapi
    build:
      context: .
      dockerfile: src/FastDeliveruu.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5233:5233
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
